import "~/styles/globals.css";

import { Inter } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";
import { Sidebar } from "./_components/navigation/side-nav";
import Topbar from "./_components/navigation/top-nav";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable}`}>
        <TRPCReactProvider>
          <Topbar />
          <div className="grid min-h-screen grid-cols-1 pt-20 md:grid-cols-4">
            <Sidebar className="hidden pt-12 md:col-span-1 md:block" />
            <div className="container mx-auto flex-1 px-4 py-10 md:col-span-3 lg:px-10">
              {children}
            </div>
          </div>
        </TRPCReactProvider>
      </body>
    </html>
  );
}